import { Inter } from 'next/font/google'
import './globals.css'
import { MyAuthProvider } from '@/hooks'
import { Toaster } from "react-hot-toast";
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-center " />
        <MyAuthProvider>
          {children}
        </MyAuthProvider>
      </body>
    </html>
  )
}
